export const nouns = [
  "accessibility",
  "AI",
  "analytics",
  "app",
  "application",
  "architecture",
  "api",
  "automation",
  "BI",
  "Big Data",
  "blockchain",
  "build time",
  "business value",
  "Caas",
  "cache",
  "CLI",
  "client",
  "cloud",
  "cluster",
  "company",
  "container",
  "content",
  "dashboard",
  "data",
  "database",
  "development",
  "domain",
  "endpoint",
  "enterprise",
  "firewall",
  "graph",
  "home office",
  "infrastucture",
  "internationalization",
  "IoT",
  "kanban",
  "lambda",
  "localization",
  "machine learning",
  "marketplace",
  "microservice",
  "ML",
  "mobile",
  "monitoring",
  "NFT",
  "performance",
  "pipeline",
  "platform",
  "quantum computing",
  "Saas",
  "sandbox",
  "scalability",
  "SCRUM",
  "server",
  "security",
  "software",
  "synergy",
  "tech",
  "technology",
  "test",
  "UI",
  "unit test",
  "UX",
  "version control",
  "VPN",
  "waterfall",
  "web",
  "WYSIWYG",
  "zero in",
];

export const adjectives = [
  "agile",
  "compliant",
  "concurrent",
  "efficient",
  "enterprise",
  "fluid",
  "headless",
  "integrated",
  "legacy",
  "modern",
  "monetize",
  "multi-faceted",
  "no-code",
  "offline",
  "online",
  "performant",
  "prerendered",
  "remote",
  "seamless",
  "serverless",
  "scalable",
  "statically generated",
  "stream",
  "sustainable",
  "transformational",
  "zero-configuration",
];

export const verbs = [
  "assert",
  "architect",
  "bootstrap",
  "build",
  "communicate",
  "compile",
  "conglomerate",
  "design",
  "destroy",
  "disrupt",
  "double-click",
  "embrace",
  "energize",
  "facilitate",
  "follow",
  "hack",
  "identify",
  "improve",
  "integrate",
  "invent",
  "iterate",
  "launch",
  "lead",
  "leverage",
  "maintain",
  "optimize",
  "organize",
  "refactor",
  "render",
  "proxy",
  "scale",
  "stream",
  "streamline",
  "subscribe",
  "synergize",
];

export const adverbs = [
  "better",
  "broader",
  "cheaper",
  "cleaner",
  "efficiently",
  "faster",
  "harder",
  "on-the-fly",
  "softer",
  "stronger",
];

export const conjunctions = ["with", "the", "of", "within"];
export const possessivePronouns = ["your", "their"];
export const withWord = ["with"];
